word_braille_map=[]
word_braille_map.append(
                    {"ar":("58",1),
                     "bb":("59",4),
                     "be":("59",2),
                     "cc":("61",4),
                     "ch":("62",1),
                     "ea":("65",4),
                     "ed":("66",1),
                     "en":("67",1),
                     "er":("69",1),
                     "ff":("70",4),
                     "gg":("72",4),
                     "gh":("73",1),
                     "in":("75",1),
                     "of":("77",1),
                     "ou":("78",1),
                     "ow":("79",1),
                     "sh":("80",1),
                     "st":("54",1),
                     "th":("55",1),
                     "wh":("84",1)})
word_braille_map.append(
                    {"and":("57",1),
                     "con":("61",2),
                     "day":("63d",1),
                     "dis":("64",2),
                     "for":("71",1),
                     "ful":("68l",3),
                     "had":("60h",1),
                     "him":("hm",1),
                     "ing":("76",1),
                     "ity":("68y",3),
                     "one":("63o",1),
                     "ong":("68g",3),
                     "the":("81",1)})
word_braille_map.append(
                    {"also":("al",1),
                     "ance":("56e",3),
                     "ence":("68e",3),
                     "ever":("63e",1),
                     "good":("gd",1),
                     "here":("63h",1),
                     "know":("63k",1),
                     "less":("56s",3),
                     "lord":("63l",1),
                     "many":("60m",1),
                     "ment":("68t",3),
                     "much":("m62",1),
                     "must":("m54",1),
                     "name":("63n",1),
                     "ness":("68s",3),
                     "ound":("6d",3),
                     "ount":("56t",3),
                     "paid":("pd",1),
                     "part":("63p",1),
                     "said":("sd",1),
                     "sion":("56n",3),
                     "some":("63s",1),
                     "such":("s62",1),
                     "time":("63t",1),
                     "tion":("68n",3),
                     "upon":("82u",1),
                     "with":("85",1),
                     "word":("82w",1),
                     "work":("63w",1),
                     "your":("yr",1)})
word_braille_map.append(
                    {"about":("ab",1),
                     "above":("abv",1),
                     "after":("af",1),
                     "again":("ag",1),
                     "below":("59l",1),
                     "blind":("bl",1),
                     "could":("cd",1),
                     "first":("f54",1),
                     "great":("grt",1),
                     "ought":("6378",1),
                     "quick":("qk",1),
                     "right":("63r",1),
                     "their":("6081",1),
                     "there":("6381",1),
                     "these":("8281",1),
                     "those":("8255",1),
                     "today":("td",1),
                     "under":("63u",1),
                     "where":("6384",1),
                     "whose":("8284",1),
                     "world":("60w",1),
                     "would":("wd",1),
                     "young":("63y",1)})
word_braille_map.append(
                    {"across":("acr",1),
                     "almost":("alm",1),
                     "always":("alw",1),
                     "before":("59f",1),
                     "behind":("59h",1),
                     "beside":("59s",1),
                     "beyond":("59y",1),
                     "cannot":("60c",1),
                     "either":("ei",1),
                     "father":("63f",1),
                     "friend":("fr",1),
                     "itself":("xf",1),
                     "letter":("lr",1),
                     "little":("ll",1),
                     "mother":("63m",1),
                     "myself":("myf",1),
                     "people":("p",1),
                     "should":("80d",1),
                     "spirit":("60s",1)})
word_braille_map.append(
                    {"against":("ag54",1),
                     "already":("alr",1),
                     "because":("59c",1),
                     "beneath":("59n",1),
                     "between":("59t",1),
                     "braille":("brl",1),
                     "deceive":("dcv",1),
                     "declare":("dcl",1),
                     "herself":("h69f",1),
                     "himself":("hmf",1),
                     "neither":("nei",1),
                     "oneself":("63of",1),
                     "perhaps":("p69h",1),
                     "rejoice":("rjc",1),
                     "receive":("rcv",1),
                     "through":("6355",1),
                     "thyself":("55yf",1),
                     "tonight":("tn",1)})
word_braille_map.append(
                    {"although":("al55",1),
                     "children":("62n",1),
                     "conceive":("61cv",1),
                     "perceive":("p69cv",1),
                     "question":("63q",1),
                     "together":("tgr",1),
                     "tomorrow":("tm",1),
                     "yourself":("yrf",1)})
word_braille_map.append(
                    {"according":("ac",1),
                     "afternoon":("afn",1),
                     "afterward":("afw",1),
                     "character":("6362",1),
                     "deceiving":("dcvg",1),
                     "declaring":("dclg",1),
                     "immediate":("imm",1),
                     "necessary":("nec",1),
                     "ourselves":("78rvs",1),
                     "rejoicing":("rjcg",1),
                     "receiving":("rcvg",1)})
word_braille_map.append(
                    {"altogether":("alt",1),
                     "conceiving":("61cvg",1),
                     "perceiving":("p69cvg",1),
                     "themselves":("81mvs",1),
                     "yourselves":("yrvs",1)})


punctuation={"'":"36",
      "*":"37",
      "[":"38",
      ":":"39",
      ",":"40",
      "_":"41",
      "~":"42",
      "...":"43",
      "!":"44",
      "-":"45",
      "#":"46",
      "(":"47",
      ".":"48",
      "?":"49",
      "\u201C":"50",
      "\u2018":"51",
      ";":"52",
      "/":"53",
      "]":"91",
      ")":"92",
      "\u201D":"93",
      "\u2019":"94",
      "@":"95"}

full_word = {"as": "z",
             "be": "59",
             "but": "b",
             "can": "c",
             "child": "62",
             "do": "d",
             "enough": "67",
             "every": "e",
             "from": "f",
             "go": "g",
             "have": "h",
             "his": "74",
             "it": "x",
             "its": "xs",
             "just": "j",
             "knowledge": "k",
             "like": "l",
             "more": "m",
             "not": "n",
             "out": "78",
             "people": "p",
             "quite": "q",
             "rather": "r",
             "shall": "80",
             "so": "s",
             "still": "54",
             "that": "t",
             "this": "301",
             "us": "u",
             "very": "v",
             "was": "83",
             "were": "72",
             "which": "84",
             "will": "w",
             "you": "y"}

